### ISSUE TITLE
Why google/flan-t5-large for query data?

### ISSUE THREAD

**Issue by limcheekin** [misbahsy/chat-your-data-self-hosted#1]
Hi there,

Thanks for sharing the code.

At https://github.com/misbahsy/chat-your-data-self-hosted/blob/master/query_data.py#L30, I find out that you chose to use `google/flan-t5-large`. Just wanna to find out why you chose this model compare to other models.

If you choose again, is this the best model for Q&A bot? Highly appreciate sharing of your insights.

Thank you.

**Comment by misbahsy** [comment]
Hi there, 

Sorry for the delay. Actually, I mainly wanted to test if the models from HF were working with this code. So I tried a few of them. But no particular reason for choosing this. 

I would highly recommend looking into the comparison of these models for various tasks and then deciding accordingly.

**Comment by limcheekin** [comment]
Thanks for your response.

My intent to look into your code is for finding code example of self-hosted chatbot without depends on Hugging Face Hub.

If you're interested, you can look into `create_embeddings.py` and `ask_question.py` for such an example created by me at https://github.com/limcheekin/flutter-gpt/tree/huggingface.
